### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/infografia-bg55-a#2]
[Infografia ciclo de vida del desarrollo de un de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-bg55-a/files/7148493/Infografia.ciclo.de.vida.del.desarrollo.de.un.de.software.pdf)

**Comment by Abraham890** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
